const INITIAL_PLAYERS = [
  "Saunders",
  "Allbury",
  "Brad",
  "Matty",
  "Tav",
  "Ross",
  "Gooch",
  "Mook",
  "Steve",
  "Rick",
  "Chris",
  "Lee"
];

const INITIAL_TEAMS = [
  { name: "Mexico", code: "mx" },
  { name: "South Korea", code: "kr" },
  { name: "South Africa", code: "za" },
  { name: "Czechia", code: "cz" },
  { name: "Canada", code: "ca" },
  { name: "Switzerland", code: "ch" },
  { name: "Qatar", code: "qa" },
  { name: "Bosnia and Herzegovina", code: "ba" },
  { name: "Brazil", code: "br" },
  { name: "Morocco", code: "ma" },
  { name: "Scotland", code: "gb-sct" },
  { name: "Haiti", code: "ht" },
  { name: "USA", code: "us" },
  { name: "Australia", code: "au" },
  { name: "Paraguay", code: "py" },
  { name: "Turkiye", code: "tr" },
  { name: "Germany", code: "de" },
  { name: "Ecuador", code: "ec" },
  { name: "Ivory Coast", code: "ci" },
  { name: "Curacao", code: "cw" },
  { name: "Netherlands", code: "nl" },
  { name: "Japan", code: "jp" },
  { name: "Tunisia", code: "tn" },
  { name: "Sweden", code: "se" },
  { name: "Belgium", code: "be" },
  { name: "Iran", code: "ir" },
  { name: "Egypt", code: "eg" },
  { name: "New Zealand", code: "nz" },
  { name: "Spain", code: "es" },
  { name: "Uruguay", code: "uy" },
  { name: "Saudi Arabia", code: "sa" },
  { name: "Cape Verde", code: "cv" },
  { name: "France", code: "fr" },
  { name: "Senegal", code: "sn" },
  { name: "Norway", code: "no" },
  { name: "Iraq", code: "iq" },
  { name: "Argentina", code: "ar" },
  { name: "Austria", code: "at" },
  { name: "Algeria", code: "dz" },
  { name: "Jordan", code: "jo" },
  { name: "Portugal", code: "pt" },
  { name: "Colombia", code: "co" },
  { name: "Uzbekistan", code: "uz" },
  { name: "DR Congo", code: "cd" },
  { name: "England", code: "gb-eng" },
  { name: "Croatia", code: "hr" },
  { name: "Panama", code: "pa" },
  { name: "Ghana", code: "gh" }
];
